language: python
python:
  - 3.6      # current default Python on Travis CI
  - 3.7
  - 3.8

install:
  - pip install .
  - pip install nose2  
script: nose2 -v

jobs:
  include:
    - stage: deploy
      python: 3.6
      script: echo "Deploy Stage" && python --version