language: python
python:
  - 3.6      # current default Python on Travis CI
  - 3.7
  - 3.8

jobs:
  include:
    - script: nose2 -v
      install:
      - pip install .
      - pip install nose2
    - stage: deploy
      python: 3.6
      script:
        - python setup.py dist
        - twine