version: "3"

services:
  tests:
    image: python:3-slim
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "pip install . && pip install nose2 && nose2 -v"

  build-pip-package:
    image: python:3-slim
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "python3 setup.py sdist"